name: Build and release Next.js web application

on:
  push:
    branches: [main]

jobs:
  build-project:
    name: Build Next.js application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM dependencies
        run: npm ci
      - name: Build static website
        run: npm run build
      - name: Upload built website
        uses: action/upload-artifact@v2
        with:
          name: static-site
          path: out/
